services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mybooks
    ports:
      - "5434:5432"
    healthcheck:
       test: [ "CMD", "pg_isready"]
       interval: 10s
       timeout: 5s
       retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node-app:
    build:
       context: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mybooks
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: